---
AllCops:
  Exclude:
    - '*.gemspec'
  TargetRubyVersion: 2.5
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
Metrics/ClassLength:
  Enabled: true
  Exclude:
    - test/**/*
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - test/**/*
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  Exclude:
    - test/**/*
